version: '3.9'

networks:
  parser_project:
    driver: bridge

services:
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_fastapi
  #   ports:
  #     - "5433:5433"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_ADDRESS: 0.0.0.0
  #     PGADMIN_LISTEN_PORT: 5433
  #     PGADMIN_DEFAULT_SERVER: postgres_db_fastapi
  #   volumes:
  #     - ./database/data/pgadmin:/var/lib/pgadmin
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 1G
  #   networks:
  #     - parser_project

  postgres_db:
    image: postgres:15
    container_name: postgres_db_fastapi
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - parser_project
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"