"""create articles table

Revision ID: 285979bccb57
Revises: 
Create Date: 2024-11-06 01:56:08.045140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285979bccb57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_name', sa.String(), nullable=False),
    sa.Column('article_content', sa.String(), nullable=False),
    sa.Column('article_link', sa.String(), nullable=False),
    sa.Column('full_name_author', sa.String(), nullable=True),
    sa.Column('author_link', sa.String(), nullable=False),
    sa.Column('datetime_attr', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name_author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
